version: '3'

services:
    php:
        build:
            context: ../phpfpm-supervisor
            dockerfile: ./docker/php/Dockerfile
        ports:
            - 80:80 # Access GUI with http://localhost:9001/
        volumes:
            - .:/phpfpm-supervisor:cached
