version: '3'
 
services:
    php:
        build:
            context: ../phpfpm-test-supervisor
            dockerfile: ./docker/php/Dockerfile
        ports:
            - 80:80 # Access GUI with http://localhost:9001/
        volumes:
            - .:/phpfpm-test-supervisor:cached